name: Trigger Integration Tests

on:
  workflow_call:
    inputs:
      workload:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        echo 'Triggering integration tests for ${{ inputs.workload }}/ ${{ inputs.image }}'
