name: Trigger Integration Tests

on:
  workflow_call:
    inputs:
      workload:
        required: true
      image:
        required: true

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        echo 'Triggering integration tests'
